name: Deploy weekly to Cloudflare Pages

on:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 오전 9시 (KST 기준)
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get today's date folder (MMDD)
        run: echo "DATE_TAG=$(date +'%m%d')" >> $GITHUB_ENV

      - name: Copy files to dist
        run: |
          mkdir -p dist/${{ env.DATE_TAG }}
          cp digital.html dist/${{ env.DATE_TAG }}/
          cp -r assets dist/${{ env.DATE_TAG }}/
          cp -r js dist/${{ env.DATE_TAG }}/
          cp -r css dist/${{ env.DATE_TAG }}/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: your-project-name
          directory: dist
